package com.yssh.scan.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yssh.scan.bean.ScanBean;

import com.yssh.scan.bean.ScanBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scanBeanDaoConfig;

    private final ScanBeanDao scanBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scanBeanDaoConfig = daoConfigMap.get(ScanBeanDao.class).clone();
        scanBeanDaoConfig.initIdentityScope(type);

        scanBeanDao = new ScanBeanDao(scanBeanDaoConfig, this);

        registerDao(ScanBean.class, scanBeanDao);
    }
    
    public void clear() {
        scanBeanDaoConfig.clearIdentityScope();
    }

    public ScanBeanDao getScanBeanDao() {
        return scanBeanDao;
    }

}
